# This is a basic workflow to help you get started with Actions

name: SNOWFLAKE_CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
  paths:
    - 'dbscripts/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-snowflake-changes-job:
   # This workflow contains a single job called "build"
   # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -name:Checkout repository
       uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Use Python 3.8.x
        uses : actions/setup-python@v2.2.1
        with :
          python-version: 3.8.x

      # Runs a set of commands using the runners shell
      - name: Run schemachange
        env:
         SF_aCCOUNT: ${{ secrets.SF_ACCOUNT }}
         SF_USERNAME: ${{ secrects_SF_USERNAME }}
         SF_ROLE: ${{ secrets_SF_ROLE }}
         SF_WAREHOUSE: ${{ secrets_SF_WAREHOUSE }}
         SF_DATEBASE: ${{ secrets_SF_DATABASE }}
         SF_SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run:
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step1: Instaling schemachange"
          pip install schemachange
          
          echo "step2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/dbscripts -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATEBASE -c $SF_DATEBASE.SCHEMACHANGE.CHANGE_HISTORY --create -change-history-table
